# Generated by Django 5.2.7 on 2025-10-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='day',
            field=models.CharField(default='Monday', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.doctor'),
        ),
    ]
