# Generated by Django 5.2.7 on 2025-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_doctoravailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
