# Generated by Django 5.2.5 on 2025-10-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_date_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('response', models.TextField(help_text='Chatbot reply when keyword is detected')),
                ('next_action', models.CharField(blank=True, help_text="Next step (like 'show_doctors', 'ask_symptoms', etc.)", max_length=50)),
            ],
        ),
    ]
