# Generated by Django 5.2.7 on 2025-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('disease', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatkeyword',
            name='next_action',
        ),
        migrations.AlterField(
            model_name='chatkeyword',
            name='keyword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatkeyword',
            name='response',
            field=models.TextField(),
        ),
    ]
