# Generated by Django 5.2.7 on 2025-10-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_symptom_remove_chatkeyword_next_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='ChatKeyword',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor',
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='disease',
            new_name='possible_disease',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='timings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
